name = "eggmaster-pro-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Bind your serverless D1 SQLite relational database
[[d1_databases]]
binding = "DB"
database_name = "eggmaster_pro_db"
database_id = "ba98f327-0ff8-42da-a23a-9af351ec7a9c"